### ISSUE TITLE
helm s3 plugin install

### ISSUE THREAD

**Issue by emre141** [koslib/helm-eks-action#14]
Is it possible to helm s3 plugin install, I would like to PR but i do not have permission

**Comment by koslib** [comment]
Hm, that's weird, you should be able to send in a PR..have you forked the repo? If not, then that could explain it.

**Comment by emre141** [comment]
No I have not forked, let me forked and create PR

**Comment by koslib** [comment]
Closing issue since it's addressed in the latest release
