### ISSUE TITLE
Problem with Deploy to EKS 1.17

### ISSUE THREAD

**Issue by luisvillalobossalgado1987** [koslib/helm-eks-action#18]
Hello everyone,
      I am having the following error:

Error: Kubernetes cluster unreachable: Get "https://37960ADD73B948642C98F7AE96AA2D50.gr7.***.eks.amazonaws.com/version?timeout=32s": getting credentials: exec plugin is configured to use API version **client.authentication.k8s.io/v1alpha1**, plugin returned version **client.authentication.k8s.io/v1beta1**

I attach my kubeconfig

Please your help.

Regards
[config-dev.txt](https://github.com/koslib/helm-eks-action/files/6897438/config-dev.txt)

**Comment by benjamin658** [comment]
It seems that the aws-cli update the Kubernetes client authentication API version.

https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst#1209

**Comment by benjamin658** [comment]
The workaround is to lock the awscli version to 1.20.8.

https://github.com/koslib/helm-eks-action/blob/c65d80e9ce22d2a08a321522700dcfd8e3ffeb25/Dockerfile#L6

```
RUN pip install 'awscli==1.20.8'
```

**Comment by koslib** [comment]
Hey all, thanks for bringing this up!

I'll take a look later in the week and issue a new version. From my PoV I see two options:
- lock awscli to `1.20.8` (quicker fix)
- allow the user to select the kubectl version they want (harder but covers all cases)

PRs are also welcome!

**Comment by plorencrstit** [comment]
@benjamin658 can you create a pull request as a hotfix?

**Comment by hdiaz-nectia** [comment]
Hi @koslib, Can you create a hotfix with the quicker solution ?

**Comment by imranq2** [comment]
Here's a PR if someone wants to accept and merge: https://github.com/koslib/helm-eks-action/pull/20

**Comment by benjamin658** [comment]
@imranq2 @plorencrstit, I forked a repository and bump cli versions.

https://github.com/BeeInventor/helm-eks-action

**Comment by benjamin658** [comment]
Hi @koslib, I created a PR, and it works fine in our CD pipeline.

**Comment by benjamin658** [comment]
> Hey all, thanks for bringing this up!
> 
> I'll take a look later in the week and issue a new version. From my PoV I see two options:
> 
> * lock awscli to `1.20.8` (quicker fix)
> * allow the user to select the kubectl version they want (harder but covers all cases)
> 
> PRs are also welcome!

In my personal perspective, the action can separate into different tags to support multiple Kubernetes versions.
Since there are many kubectl versions that address specific Kubernetes versions.

https://docs.aws.amazon.com/zh_tw/eks/latest/userguide/install-kubectl.html

**Comment by koslib** [comment]
@benjamin658 I've merged your PR, thanks for the contribution too! The new version is out with tag [v1.9.0](https://github.com/koslib/helm-eks-action/releases/tag/v1.9.0). 

Closing this issue and monitoring it. A proper longer-term solution will be available at some point since this crisis is averted for now.
