### ISSUE TITLE
Dockerhub Caching

### ISSUE THREAD

**Issue by oriarditi** [koslib/helm-eks-action#31]
Hey
This is one of the most useful and simple actions out there 👏 

Any chance we can use dockerhub to cache it?
My runners are spending 50s building it every run.

Cheer! 🍻

**Comment by koslib** [comment]
This is actually a very good suggestion :) Thanks for bringing this up, I'll work on it quite soon (<2d)!

**Comment by koslib** [comment]
@oriarditi Down to 10s :) Enjoy!
