### ISSUE TITLE
Kubeconfig user entry is using deprecated API version client.authentication.k8s.io/v1alpha1

### ISSUE THREAD

**Issue by Sharlie89** [koslib/helm-eks-action#38]
Hi, today I started to get this issue when trying to deploy to my K8s cluster from GH-actions:

`Kubeconfig user entry is using deprecated API version client.authentication.k8s.io/v1alpha1. Run 'aws eks update-kubeconfig' to update.`

As far as I've see, this happens when you uses awscli < 1.24

This is my first time using your solution, but I think that the problems come from the docker image that you are using on "/dockerhub/Dockerfile". There's an argument where you set the AWS CLI version
`ARG AWSCLI_VERSION="1.23.13"
`
It should be greater than 1.24 or 2.7 if you are working with an EKS cluster version => 1.22

There's a plan for upgrade it? 

Thanks in advance

**Comment by koslib** [comment]
Hello, thanks for bringing this up!

I’ll send a fix during the day :)

**Comment by Sharlie89** [comment]
Thanks you for take care of this :)

**Comment by koslib** [comment]
Closed in #39 and issued release v1.25.3 - let me know if you have any issues!

**Comment by Sharlie89** [comment]
Is working, thanks @koslib !

**Comment by prachimantri212** [comment]
How to resolve this issue?

**Comment by koslib** [comment]
@prachimantri212 which version are you using?
