### ISSUE TITLE
GitHub Actions Deprecating save-state and set-output commands

### ISSUE THREAD

**Issue by kkurzyk** [koslib/helm-eks-action#52]
[https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

```
entrypoint.sh
echo "::set-output name=response::$response"
```

**Comment by koslib** [comment]
Hello! Would you like to submit a PR about this? :)
