### ISSUE TITLE
Fix warning `set-output` command is deprecated

### ISSUE THREAD

**Issue by azeemchauhan** [koslib/helm-eks-action#53]
GitHub action updates from Node12 to Node 16 start giving the following warning/s-

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by koslib** [comment]
Awesome, thanks for this PR! I'll make sure to take a look asap!
