### ISSUE TITLE
Arch: arm64

### ISSUE THREAD

**Issue by rodrigo-oliveira-silva** [koslib/helm-eks-action#63]
i saw that only support arch:x64, is this possible add another architecture arm64?

https://hub.docker.com/r/koslib/ga-helm-eks/tags

I tried used arm64 and doesn't work

```
#0 building with "default" instance using docker driver
  
  #1 [internal] load .dockerignore
  #1 transferring context: 2B done
  #1 DONE 0.0s
  
  #2 [internal] load build definition from Dockerfile
  #2 transferring dockerfile: 283B 0.0s done
  #2 DONE 0.0s
  
  #3 [internal] load metadata for docker.io/koslib/ga-helm-eks:2.5
  #3 ERROR: no match for platform in manifest sha256:b363b7b7ceca29694303443460ab97d3e9916f679bf971b34b1127a88ff3c5a4: not found
  ------
   > [internal] load metadata for docker.io/koslib/ga-helm-eks:2.5:
  ------
  Dockerfile:4
  --------------------
     2 |     # please open a PR for the `dockerhub/Dockerfile` in the same project.
     3 |     
     4 | >>> FROM koslib/ga-helm-eks:2.5

```

**Comment by koslib** [comment]
Hello! Would you be able to submit a PR for this potentially? Otherwise it might take me some time to get on this unfortunately :(

**Comment by rodrigo-oliveira-silva** [comment]
Please verify my pr...

**Comment by rodrigo-oliveira-silva** [comment]
@koslib , 

follow PR [64](https://github.com/koslib/helm-eks-action/pull/64)

**Comment by AsafZoki** [comment]
is this PR going to be merged I'm using linux/arm64 arch and I cant find any action like this that support this arch

**Comment by koslib** [comment]
Just merged it and released https://github.com/koslib/helm-eks-action/releases/tag/v1.29.0
