### ISSUE TITLE
Support using aws CLI's eks update-kubeconfig command

### ISSUE THREAD

**Issue by erran** [koslib/helm-eks-action#8]
👋🏽 Hey @koslib what are your thoughts on leveraging [update-kubeconfig](https://docs.aws.amazon.com/cli/latest/reference/eks/update-kubeconfig.html) as per Amazon's [Create kubeconfig](https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html) documentation? I'd be happy to contribute if it's something you're interested in.

We'd be able to optionally use this over `KUBE_CONFIG_DATA` using a few new arguments under `with:` like so:
1.  `cluster_name` which is passed into the update-kubeconfig command's `--name` argument.
2. `update_kubeconfig_path` which if supplied is passed into the update-kubeconfig command's `--kubeconfig` argument.

```
# generates kubeconfig in the default kubeconfig location
aws eks --region us-east-1 update-kubeconfig --name my-staging-cluster

# generates kubeconfig in the specified location
aws eks --region us-east-1 update-kubeconfig --name my-staging-cluster --kubeconfig kubeconfig-staging
```

**Comment by erran** [comment]
Closing since this appears to be a functional way to add a simple step to accomplish my goal: https://github.com/WyriHaximus/github-action-helm3/issues/18#issuecomment-698582423

```yaml
      - name: Generate kubeconfig
        id: generate-kubeconfig
        run: |-
          aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name ${{ env.CLUSTER_NAME }}
          KUBECONFIG="$(cat ~/.kube/config)"
          KUBECONFIG="${KUBECONFIG//'%'/'%25'}"
          KUBECONFIG="${KUBECONFIG//$'\n'/'%0A'}"
          KUBECONFIG="${KUBECONFIG//$'\r'/'%0D'}"
          echo "::set-output name=kubeconfig::$KUBECONFIG"
```

Since similar to how it is described in that issue this is a docker action I'll close this out. 😄

**Comment by koslib** [comment]
Hello @erran, this is actually great stuff! I hadn't thought of that at all to be honest, but it seems like a great option to have. Do you think contributing docs in this action for this would be useful for other users too? If yes, feel free to send in a PR and we can discuss further if "internal" support for this would make more sense in the future!

Thanks for the great idea once again!

**Comment by erran** [comment]
I’d be happy to contribute a docs update around this and I’ll make sure to include how I was able to use the output with this action. 😃

**Comment by erran** [comment]
Dropping this as a note to myself/others for tracking — I also found https://github.com/actions-hub/gcloud/issues/11 when I got an error from this action `base64: truncated base64 input`. My above snippet will need to be updated to base64 encode the output.

**Comment by erran** [comment]
Sorry for not updating anyone sooner. In my use case I ended up using the built-in `helm` binary instead of this action due to issues using the KUBECONFIG environment variable regardless of what I tried with base64 decoding/replacing newlines.
