### ISSUE TITLE
Build koslibpro/helm-eks-action@master fail

### ISSUE THREAD

**Issue by luisvillalobossalgado1987** [koslib/helm-eks-action#9]
Today the action began to fail.
The github workflow shows us errors related to python:

Collecting PyYAML<5.5,>=3.10
	Downloading PyYAML-5.4.1.tar.gz (175 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /usr/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-icr6mutl/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel Cython

	ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-r8vmoxib/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel Cython Check the logs for full command output.
	The command '/bin/sh -c pip install awscli' returned a non-zero code: 1
[3_Build koslibprohelm-eks-action@master.txt](https://github.com/koslib/helm-eks-action/files/6313337/3_Build.koslibprohelm-eks-action%40master.txt)

**Comment by mcandio** [comment]
@koslib We are facing the same problem, would you be so awesome to take a look at this?

**Comment by joaovitorsramos** [comment]
@koslib please help us here, same problem.

**Comment by mcandio** [comment]
I think you can fix it by setting a PyYaml like mentioned here:
[https://github.com/aws/aws-cli/issues/6094#issuecomment-819808464](url)

**Comment by TediPapajorgji** [comment]
I've got a hacked together solution here:
https://github.com/koslib/helm-eks-action/pull/10

**Comment by koslib** [comment]
Hey all, I'm aware of the issue and trying to look into it. 

@TediPapajorgji I appreciate you sending in an MR with a workaround, however I suggest we take a step back to figure out a proper solution. Shall this is not the case until tomorrow mid-day, I'll merge your MR as an intermediary solution until a proper fix is out. Sounds good?

**Comment by TediPapajorgji** [comment]
> Hey all, I'm aware of the issue and trying to look into it.
> 
> @TediPapajorgji I appreciate you sending in an MR with a workaround, however I suggest we take a step back to figure out a proper solution. Shall this is not the case until tomorrow mid-day, I'll merge your PR as an intermediary solution until a proper fix is out. Sounds good?
> 
> And ofc whoever else feels like it can send in a patching PR.

Yes of course sounds good. I wanted to get something out there - it was a blocker on our end and maybe for others as well.

**Comment by koslib** [comment]
Circling back here after a brief elaboration on the issue - so I submitted this: https://github.com/koslib/helm-eks-action/pull/11, could anyone take a look for a sanity check? The image seems to build on my local test at least so hopefully this solves our problem here. 

Let me know!

**Comment by mcandio** [comment]
> Circling back here after a brief elaboration on the issue - so I submitted this: #11, could anyone take a look for a sanity check? The image seems to build on my local test at least so hopefully this solves our problem here.
> 
> Let me know!

Checked,  It seems to work properly.

**Comment by koslib** [comment]
Just merged to `master` branch and issued release `v1.7.0` (https://github.com/koslib/helm-eks-action/releases/tag/v1.7.0). Thanks all for the great collab and fast reflexes!

**Comment by luisvillalobossalgado1987** [comment]
Thank you very much to all. The github workflows are already working correctly.
